var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import styled, { css } from 'styled-components';
import { Button as MuiButton } from '../Button';
var IconButtonSizeVariants = {
    small: css(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n    padding: 0 17px;\n    height: 36px;\n    width: 36px;\n    \n    .MuiButton-label {\n      font-size: 18px;\n      line-height: 18px;\n      width: 18px;\n    }\n    \n    .MuiButton-startIcon > *:first-child {\n      width: 18px;\n      height: 18px;\n      font-size: 18px;\n    }\n  "], ["\n    padding: 0 17px;\n    height: 36px;\n    width: 36px;\n    \n    .MuiButton-label {\n      font-size: 18px;\n      line-height: 18px;\n      width: 18px;\n    }\n    \n    .MuiButton-startIcon > *:first-child {\n      width: 18px;\n      height: 18px;\n      font-size: 18px;\n    }\n  "]))),
    medium: css(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n    padding: 0 23px;\n    height: 48px;\n    width: 48px;\n  \n    .MuiButton-label {\n      width: 20px;\n      font-size: 20px;\n      line-height: 20px;\n    }\n\n    .MuiButton-startIcon > *:first-child {\n      width: 20px;\n      height: 20px;\n      font-size: 20px;\n    }\n  "], ["\n    padding: 0 23px;\n    height: 48px;\n    width: 48px;\n  \n    .MuiButton-label {\n      width: 20px;\n      font-size: 20px;\n      line-height: 20px;\n    }\n\n    .MuiButton-startIcon > *:first-child {\n      width: 20px;\n      height: 20px;\n      font-size: 20px;\n    }\n  "]))),
    large: css(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n    padding: 0 27px;\n    height: 56px;\n    width: 56px;\n  \n    .MuiButton-label {\n      width: 24px;\n      font-size: 24px;\n      line-height: 24px;\n    }\n    \n    .MuiButton-startIcon > *:first-child {\n      width: 24px;\n      height: 24px;\n      font-size: 24px;\n    }\n  "], ["\n    padding: 0 27px;\n    height: 56px;\n    width: 56px;\n  \n    .MuiButton-label {\n      width: 24px;\n      font-size: 24px;\n      line-height: 24px;\n    }\n    \n    .MuiButton-startIcon > *:first-child {\n      width: 24px;\n      height: 24px;\n      font-size: 24px;\n    }\n  "]))),
};
var IconButtonColorVariants = {
    outlined: css(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n     ", ";\n  "], ["\n     ", ";\n  "])), function (_a) {
        var _b = _a.theme.custom.lightTheme.colors, _c = _b.button, backgroundColor = _c.backgroundColor, borderColor = _c.borderColor, borders = _b.borders, typographyAndIcons = _b.typographyAndIcons;
        return css(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n        border: 1px solid ", ";\n        background-color: ", ";\n        &:hover {\n          box-shadow: none;\n          background-color: ", ";\n          border-color:  ", ";\n        }\n\n        &:focus {\n          box-shadow: none;\n          background-color: ", ";\n          border-color:  ", ";\n        }\n\n        &:active {\n          background-color: ", ";\n          border-color:  ", ";\n        }\n\n        &:disabled {\n          background-color: ", ";\n          border-color:  ", ";\n        }\n\n       .MuiButton-label {\n          color: ", ";\n          border-color:  ", ";\n       }\n     "], ["\n        border: 1px solid ", ";\n        background-color: ", ";\n        &:hover {\n          box-shadow: none;\n          background-color: ", ";\n          border-color:  ", ";\n        }\n\n        &:focus {\n          box-shadow: none;\n          background-color: ", ";\n          border-color:  ", ";\n        }\n\n        &:active {\n          background-color: ", ";\n          border-color:  ", ";\n        }\n\n        &:disabled {\n          background-color: ", ";\n          border-color:  ", ";\n        }\n\n       .MuiButton-label {\n          color: ", ";\n          border-color:  ", ";\n       }\n     "])), borders.border, backgroundColor.outlined.active, backgroundColor.outlined.hovered, borderColor.outlined.hovered, backgroundColor.outlined.focused, borderColor.outlined.focused, backgroundColor.outlined.pressed, borderColor.outlined.pressed, backgroundColor.outlined.active, borderColor.outlined.active, typographyAndIcons.default.active, borderColor.outlined.disabled);
    }),
    plain: css(templateObject_7 || (templateObject_7 = __makeTemplateObject(["\n    ", ";\n  "], ["\n    ", ";\n  "])), function (_a) {
        var _b = _a.theme.custom.lightTheme.colors, backgroundColor = _b.button.backgroundColor, states = _b.states;
        return css(templateObject_6 || (templateObject_6 = __makeTemplateObject(["\n      border: none;\n      \n      &:hover {\n        background-color: ", ";\n      }\n\n      &:focus {\n        box-shadow: none;\n        background-color: ", ";\n      }\n\n      &:active {\n        background-color: ", ";\n      }\n\n      &:disabled {\n        background-color: ", ";\n      }\n\n      .MuiButton-label {\n        color: ", ";\n      }\n      \n    "], ["\n      border: none;\n      \n      &:hover {\n        background-color: ", ";\n      }\n\n      &:focus {\n        box-shadow: none;\n        background-color: ", ";\n      }\n\n      &:active {\n        background-color: ", ";\n      }\n\n      &:disabled {\n        background-color: ", ";\n      }\n\n      .MuiButton-label {\n        color: ", ";\n      }\n      \n    "])), states.hover, backgroundColor.plain.focused, backgroundColor.outlined.pressed, backgroundColor.outlined.disabled, function (props) { return props.theme.custom.lightTheme.colors.typographyAndIcons.default.active; });
    }),
};
export var StyledIconButton = styled(MuiButton)(templateObject_10 || (templateObject_10 = __makeTemplateObject(["\n  min-width: 36px;\n  padding: 0;\n  color: ", ";\n  .MuiButton-startIcon span:first-child {\n    padding-right: 0;\n  }\n  ", ";\n  ", ";\n"], ["\n  min-width: 36px;\n  padding: 0;\n  color: ", ";\n  .MuiButton-startIcon span:first-child {\n    padding-right: 0;\n  }\n  ", ";\n  ", ";\n"])), function (props) { return props.theme.custom.lightTheme.colors.typographyAndIcons.default.active; }, function (_a) {
    var _b = _a.size, size = _b === void 0 ? 'small' : _b;
    return css(templateObject_8 || (templateObject_8 = __makeTemplateObject([" ", "; "], [" ", "; "])), IconButtonSizeVariants[size]);
}, function (_a) {
    var _b = _a.assign, assign = _b === void 0 ? 'outlined' : _b;
    return css(templateObject_9 || (templateObject_9 = __makeTemplateObject([" ", "; "], [" ", "; "])), IconButtonColorVariants[assign]);
});
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6, templateObject_7, templateObject_8, templateObject_9, templateObject_10;
